### ISSUE TITLE
Toggl service might need an update

### ISSUE THREAD

**Issue by izuzak** [github/github-services#1007]
The toggl service is making requests to `https://www.toggl.com/api/v8/tasks.json`

https://github.com/github/github-services/blob/95a0136431689f3c0e965fb2c6386a2684892050/lib/services/toggl.rb#L18

However, that URL is returning a 404, which is unexpected:

```
$ curl https://www.toggl.com/api/v8/tasks.json -i -X POST -d ""
HTTP/1.1 404 Not Found
```

But, if I try making a request to this URL -- https://www.toggl.com/api/v8/tasks -- then the request returns a 403, which is expected because I didn't authenticate:

```
$ curl https://www.toggl.com/api/v8/tasks -i -X POST -d ""
HTTP/1.1 403 Forbidden
```

So, it seems that the `tasks.json` worked at some point, but after that stopped working and just `tasks` should be used now.

@refiito can you help us confirm what needs to be updated here? Thanks! :bow: Also cc @github/hooks and @aronpedersen

**Comment by refiito** [comment]
From first glance (api v8 was quite a considerable change compared to v6, hence the version bump didn't work...)

time entry creation should be something in the line of:
```
http_post "time_entries", generate_json(
        :time_entry => {
          :duration => duration.to_i,
          :description => commit["message"].strip,
          :pid => data["project"],
          :start => (Time.now - duration.to_i).iso8601,
          :billable => true, # this is a pro feature, will be ignored for free version users
          :created_with => "github",
          :stop => Time.now.iso8601
        }
      )
```
(some helpful reference: https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md#create-a-time-entry)

**Comment by izuzak** [comment]
@refiito Thanks! Just to make sure -- are the old `tasks` (what the service is currently creating) the new `time_entries` (what your snippet is using)?

**Comment by refiito** [comment]
@izuzak yes, what used to be called tasks in prior API versions are now time_entries (and yes, there are also tasks in the current version to add to the confusion)

**Comment by aronpedersen** [comment]
Any progress on this here? 
 
Date: Fri, 9 Jan 2015 09:23:18 -0800

**Comment by kdaigle** [comment]
We rely on the community to make changes to the services in this repository. Is anyone around/interested in helping work fix this Toggl bug?

**Comment by kdaigle** [comment]
@refiito would you be willing to open a PR to make the necessary change? Based on what I'm reading above, does this mean the Toggle service is not working for anyone who has it installed?

**Comment by kdaigle** [comment]
Fixed by https://github.com/github/github-services/pull/1073! :sparkles: Thanks again @refiito! :confetti_ball:
