### ISSUE TITLE
Suggested changes for irc.rb to make it more easier to find out who owns the bot (add user/repo in realname).

### ISSUE THREAD

**Issue by Zarthus** [github/github-services#1016]
Hi,

On our IRC network we have an issue with the Github IRC hook, a bot that keeps identifying to a name it does not own generates both annoyance for us as well the owner of the account. Because it is impossible for network operators to identify who owns the bot. I have written a small suggested change that adds the repository name and github account owner to the realname of the bot.

However, as I was writing the patch, my inexperience with ruby made it impossible to finish the originally intended pull request, and without the ability to properly test this, I'd like to appeal to the maintainer of the service (which seems to be @technoweenie) to verify if this will work, or is willing to integrate this on their own.

With that in mind, there is an issue at hand.  Private repositories will be visible in the realname. I think this issue is pretty trivial and it is the users own choice to enable the hook.  However I am willing to see if there are better alternative ways to implement this instead (perhaps by not mentioning the repo name, but just the user name). Alternatively it may be an idea to include the channel, but those can come in quantity, and may reveal secret channels due to this.

With this in mind, the suggested patch is below. But I was stuck at the stage where I could fully test my patch to make sure it actually works.

```diff
diff --git a/lib/services/irc.rb b/lib/services/irc.rb
index 4596bef..98bbc89 100644
--- a/lib/services/irc.rb
+++ b/lib/services/irc.rb
@@ -61,7 +61,7 @@ class Service::IRC < Service

     irc_password("PASS", data['password']) if !data['password'].to_s.empty?
     irc_puts "NICK #{botname}"
-    irc_puts "USER #{botname} 8 * :GitHub IRCBot"
+    irc_puts "USER #{botname} 8 * :#{irc_format_realname}"

     loop do
       case irc_gets
@@ -276,6 +276,12 @@ class Service::IRC < Service
     "#{fmt_name commit['author']['name']}: #{short}"
   end

+  def irc_format_realname
+    "#{repo.name}/#{sender.login} - Github IRCBot"
+  rescue
+    "Github IRCBot"
+  end
+
   def irc_issue_summary_message
```

Please consider implementing this patch to make it easier for IRC administrators and operators around the world to identify who the bot belongs to, so that they can contact the owner, and make them aware of the issue.

**Comment by kdaigle** [comment]
@Zarthus thanks for this! @technoweenie no longer works on this repository. I'm hopeful someone else in the community can work on this and transform it into a Pull Request.
