### ISSUE TITLE
If commit message refers to issue, add link and issue title

### ISSUE THREAD

**Issue by vhuber** [github/github-services#1021]
Hi there,

Imagine that :
```
git commit -m "#42 @user check that"
git push
```
A mail will be generated with the message, and I will be able to follow the link to the commit.
It should be convenient to add the title of the issue and the link to the issue directly.

All the best,

VH.

**Comment by kdaigle** [comment]
@vhuber you could totally build something like that with [webhooks](https://developer.github.com/webhooks/). This doesn't sound like something we'd be looking to add as a service because we already have an Email service we support.

Take a look at the documentation and feel free to contact support@github.com if you need any help. :grinning:

**Comment by vhuber** [comment]
@kdaigle Thank you for the answer. Actually, I'm confused since I contacted first support@github.com and I got the following answer
```
Hi Vincent,

> Is it possible to add the link to the referenced issue in the mail ?

Thanks for the suggestion. It looks like you're referring to an email sent by the Email Service (not a standard notification). The source code for this service is available here:

https://github.com/github/github-services/blob/master/lib/services/email.rb

So that's where the change would need to be made if this were to be implemented. You could open an issue or pull request.

Thanks,
James
```

Thus, I guess my question is not about building something new but parsing the `commit["message"]` variable line 242 in [email.rb](https://github.com/github/github-services/blob/master/lib/services/email.rb) to add a link.

I apologize for the non understandable question :/

**Comment by kdaigle** [comment]
@vhuber I'm sorry. To clarify, you'd like the email to link directly to that commit in GitHub's UI?

**Comment by vhuber** [comment]
@kdaigle If the commit' message contains an issue's reference, it would be nice to add the link (in the mail) to the issue in GitHub's UI. We already have links to commits in the mail.

**Comment by vhuber** [comment]
@kdaigle Is there something we can do for that purpose ?

**Comment by kdaigle** [comment]
We'll take a look at it and see if it's something we can add moving forward. Now I understand what you're looking for though. :grinning:
