### ISSUE TITLE
XMPP host/port setting 

### ISSUE THREAD

**Issue by hhaidar** [github/github-services#1022]
Hey there,

Would it be possible to add a host and port setting to the XMPP MUC service? The `connect` method should accept host and port: https://github.com/github/github-services/blob/master/lib/services/xmpp_muc.rb#L34

**Comment by kdaigle** [comment]
cc @lloydwatkin

**Comment by lloydwatkin** [comment]
Hey @hhaidar, I hadn't built the two plugins to work on a different host or non-standard port but certainly this is something I can add. @kdaigle I'll get this coded up ASAP and make a new PR. Lloyd.

**Comment by hhaidar** [comment]
@lloydwatkin awesome, you're the best :)

**Comment by lloydwatkin** [comment]
Pull request made :)

**Comment by lloydwatkin** [comment]
@hhaidar thanks, but I wouldn't go that far ;)
