### ISSUE TITLE
Will new service integrations be accepted?

### ISSUE THREAD

**Issue by Restless-ET** [github/github-services#1041]
I have a webhook that I would like to register as a new service. However during my investigation I've run across [this](https://developer.github.com/webhooks/#service-hooks) (please refer to the **Note** at the bottom).

I've noticed that there are a few pendings PRs here that add new services so I've started to wonder if what's stated on that note is already/still taking place. I really don't want to start creating a new service integration that will never be accepted...

Being so, would anyone be kind enough to confirm this for me? Are new services no longer accepted? If they are, will they ever be again?
Thanks in advance.

Best regards,

**Comment by heitortsergent** [comment]
:+1: Also curious about this. I was just gonna start working on a Keen IO integration.

**Comment by kdaigle** [comment]
Sorry for the delay in getting back to you! You are correct: we are [no longer accepting new services](https://github.com/github/github-services/blob/master/CONTRIBUTING.md) and would recommend you go the approach of an OAuth application and webhook setup. The [CONTRIBUTING.md](https://github.com/github/github-services/blob/master/CONTRIBUTING.md) can point you in the right direction. :sparkles:

**Comment by Restless-ET** [comment]
Very well. I guess I'll look into the OAuth option then. :)

Thanks for the confirmation on this.

Best regards,

**Comment by heitortsergent** [comment]
:+1:
