### ISSUE TITLE
HerokuBeta service + hubot-deploy integration

### ISSUE THREAD

**Issue by a-warner** [github/github-services#1043]
I setup hubot-deploy such that I can confirm that it's successfully creating GitHub deployments via the API (I hit the API directly via curl to confirm). I setup the `HerokuBeta` service per [these instructions](https://github.com/github/github-services/blob/master/docs/herokubeta) and it does seem to have created a deployment, but I'm not sure it's actually doing anything.

I ended up with a heroku deployment notification which claims to have deployed, but there are no actual changes to the app (i.e. the latest commit on master is not actually deployed, which I confirmed both by checking for the feature I deployed and by `fetch`ing the remote and checking the head commit).

Here is the deployment notification (app/account name redacted):

```
user@domain.com deployed master@ to heroku-app-name
```

note the `master@` with no `sha`.. usually these deploy notifications look like

```
user@domain.com deployed 01f6f51 to heroku-app-name
```

where `01f6f51` is the sha of the commit that was deployed.

There also are no statuses on any of the deploys that the `HerokuBeta`service has claimed to deploy, and hubot never actually confirms the deploy completed. (not sure if that's supposed to work out of the box anyway or if I have to configure heroku to do something there)

Anyway, I'm happy to give you more info, but I'm not sure exactly what to provide since I can't see the logs of what the `HerokuBeta` service actually did. (or maybe I can somehow?)

**Comment by atmos** [comment]
Can you email the repo in question to support@github.com so we can take a look? I'm using this successfully for a lot of personal projects so there's probably something misconfigured somewhere.
