### ISSUE TITLE
Consistent naming for Amazon services.

### ISSUE THREAD

**Issue by UnquietCode** [github/github-services#1053]
Hi folks. If it's easy, consistent naming of the Amazon AWS services would be helpful. Right now the naming of those services is as follows:

```
OpsWorks => 'AWS OpsWorks'
CodeDeploy => 'AWS CodeDeploy'
SNS => 'AmazonSNS'
SQS => 'SqsQueue'
```

Thanks!

**Comment by kdaigle** [comment]
If someone wants to tackle changing the `title` of each service to match a consistent AWS based naming scheme, that'd be :sparkles:.

**Comment by UnquietCode** [comment]
Rockin! You're right that Amazon seems oddly particular about their names, but now they match up. Thanks!
