### ISSUE TITLE
Does the GitHub Bamboo Service support Bamboo Cloud?

### ISSUE THREAD

**Issue by seth-reeser** [github/github-services#1067]
Despite receiving a `Last delivery was successful.` the Bamboo Cloud Build Plan is not firing.

I am using:

* *Base url* `devopsgroup-io.atlassian.net`
* *Base key* `DRM-DT`
* *Username* `********`
* *Password* `********`
* *Active* `true`

**Comment by kdaigle** [comment]
Can you please go to https://github.com/contact and submit a request there? We'll be better able to help individual installs there?
