### ISSUE TITLE
Clarification on new services

### ISSUE THREAD

**Issue by dehora** [github/github-services#1071]
Hi, apologies for opening a non-code issue, but I wasn't clear on whether github services is accepting new services

Over in https://developer.github.com/webhooks/#service-hooks it says

> Note: If you are building a new integration, you should build it as webhook. We suggest creating an OAuth application to automatically install and manage your users’ webhooks. We will no longer be accepting new services to the github-services repository.

and in https://github.com/github/github-services/blob/master/CONTRIBUTING.md it says

> NOTE: GitHub no longer accepts new services that are based on HTTP. If you'd like to integrate your application or service with GitHub, you should use webhooks which will POST a payload to your server for each event.

Does this mean github-services is no longer accepting services at all to display or [appear in the api](https://api.github.com/hooks), or will now only consider ones based on webhooks?

**Comment by pengwynn** [comment]
> apologies for opening a non-code issue

@dehora No need to apologize. Issues are issues. :grinning: 

> Does this mean github-services is no longer accepting services at all to display or appear in the api, or will now only consider ones based on webhooks?

We're no longer accepting new services to display in the UI or to list in the API that are based on HTTP. Webhooks provide far greater flexibility for integrators to build and maintain those integrations. 

Does that help?

**Comment by pengwynn** [comment]
@dehora [Let us know][] if you have questions about building your integration. Gonna close this out.

[Let us know]: http://git.io/v3DOE

**Comment by supriyantomaftuh** [comment]
Please unregister my accaount at our company or relationship after free limit day off free register. Thanks.

Thanks,

Supriyanto Maftuh.
