### ISSUE TITLE
Event type is lost for Amazon SNS hook

### ISSUE THREAD

**Issue by leelynne** [github/github-services#1076]
When using the Amazon SNS webservice hook the payload does not contain the event type.  The normal X-Github-Event http header is lost.  This makes it very difficult to parse generic events for receivers. 

The X-Github-Event should ideally be SNS [message attribute](http://docs.aws.amazon.com/sns/latest/APIReference/API_Publish.html).  I wrote a patch to do that but then noticed the guidelines.  

Would it be possible to update the AmazonSNS hook to the event type in some way?

**Comment by kdaigle** [comment]
Given the event is intended to be passed along to services, I think this would be an OK "bug fix" to fix in a way that SNS should receive it. It sounds like a message attribute. :smile: We'd love a PR to solve this.

**Comment by kdaigle** [comment]
This was fixed by https://github.com/github/github-services/pull/1078.
