### ISSUE TITLE
Shorter and/or template-based IRC messages

### ISSUE THREAD

**Issue by headius** [github/github-services#1080]
We love having the github IRC messages for JRuby, but some of our channel members complain that they are too noisy. I am proposing some improvements (which I'll try to work on myself).

1. Template-based IRC messages, similar to Travis CI. For example, most of our channel members don't need to see the full name of the committer every time. This would also allow us to customize the colors used in the messages.
2. Single-line messages for single commit pushes. Many of our committers frequently push single commits. This ends up being needlessly noisy in the channel.

Any thoughts on this?

**Comment by headius** [comment]
An example of the noisy duplication in a single commit message:

```
GitHub169: [jruby-openssl] headius pushed 1 new commit to master: http://git.io/vsnqN
GitHub169: jruby-openssl/master bb2cda2 Charles Oliver Nutter: Enable travis messages without join.
```

* The repository and branch are unnecessarily displayed n + 1 times where n = number of commits up to three.
* Both the committer's username and full name are displayed. If there are multiple commits, the full name is displayed n times.
* The fact that there's a single commit is evident from the single commit message.

I'd propose a single commit could be formatted like this:

```
[jruby-openssl] headius pushed to master: bb2cda2 "Enable travis messages without join." http://git.io/vsnqN
```

Since the majority of pushes are going to be "normal" pushes, we could also remove that:

```
[jruby-openssl] headius: bb2cda2 "Enable travis messages without join." http://git.io/vsnqN
```

This format is compact enough that it could be used for n messages, with an n+1 message indicating there are more commits:

```
[jruby-openssl] headius: bb2cda2 "Commit 1" http://git.io/abcd1
[jruby-openssl] headius: bb2cda3 "Commit 2" http://git.io/abcd2
[jruby-openssl] headius: bb2cda4 "Commit 3" http://git.io/abcd3
[jruby-openssl] headius: +5 more commits
```

**Comment by kdaigle** [comment]
> Template-based IRC messages, similar to Travis CI. For example, most of our channel members don't need to see the full name of the committer every time. This would also allow us to customize the colors used in the messages.

I'm not sure templating would be particularly user friendly in the current GitHub services workflow. I'd have to think a lot more seriously about that before going down that route.

> Single-line messages for single commit pushes. Many of our committers frequently push single commits. This ends up being needlessly noisy in the channel.

The one trick (which, admittedly, templating could fix) with making changes to the IRC service is that everyone who uses the IRC service is going to have a strong opinion about what the content looks like. For example, your simpler commit message now doesn't mention the branch. I could see several users of the IRC service being upset with that.

Anyone else that uses the IRC service have an opinion on these changes?

**Comment by AlissaSquared** [comment]
> For example, your simpler commit message now doesn't mention the branch.

That was a second proposed option for someone who prefers to only push to one branch.
If someone wanted to push to multiple branches they should change it to support multiple branches.
I actually kinda like this idea. It would help with the clunk of my working spam. \:)

**Comment by mikemcquaid** [comment]
We're only accepting bug/security fixes to existing services now, sorry! See https://github.com/github/github-services/blob/master/CONTRIBUTING.md#updating-an-existing-service for more details.
