### ISSUE TITLE
Returns a 400 Bad Request response to the non-URL encoded request on the Github Pages.

### ISSUE THREAD

**Issue by MiCHiLU** [github/github-services#1085]
It should fix the behavior of the HTTP clients.
However, the crawler of like the facebook come accessed via non-URL-encoded.
It will be a big problem in some countries.

Now, the Github Pages returns a 400 Bad Request response to the non-URL-encoded request on the Github Pages, as below:

    $ curl -sv "http://www.github.io/日本語" >/dev/null
    * Connected to www.github.io (103.245.222.133) port 80 (#0)
    > GET /日本語 HTTP/1.1
    > Host: www.github.io
    > User-Agent: curl/7.43.0
    > Accept: */*
    >
    < HTTP/1.1 400 Bad Request
    < Content-Type: text/html
    < Date: Sun, 30 Aug 2015 07:56:26 GMT
    < Via: 1.1 varnish
    ...

I'm hope a 301 Moved Permanently response for redirect to URL-encoded(based UTF-8) that is like the WikiPedia as below:

    $ curl -sv "https://ja.wikipedia.org/wiki/日本語" >/dev/null
    * Connected to ja.wikipedia.org (198.35.26.96) port 443 (#0)
    > GET /wiki/日本語 HTTP/1.1
    > Host: ja.wikipedia.org
    > User-Agent: curl/7.43.0
    > Accept: */*
    >
    < HTTP/1.1 301 Moved Permanently
    < Server: nginx/1.9.3
    < Date: Sun, 30 Aug 2015 07:58:09 GMT
    < Content-Type: text/html; charset=utf-8
    < Location: https://ja.wikipedia.org/wiki/%E6%97%A5%E6%9C%AC%E8%AA%9E
    < Via: 1.1 varnish, 1.1 varnish, 1.1 varnish
    ...

Thank you.

**Comment by kdaigle** [comment]
If I'm understanding this issue correctly, I'm not sure it is specific to `github-services`. Could you contact https://github.com/support to report the issue directly? Thanks! If this is specific to `github-services`, could you clarify what service it impacts? :smile:
