### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by jean-christophe-manciot** [github/github-services#1088]
No problem committing up until today:
![authentication issue](https://cloud.githubusercontent.com/assets/13176858/9606489/f3493eca-50c3-11e5-9a44-e9975844eaf1.jpg)
I have not changed anything, using the same token to access my account from SmartGit.

**Comment by kevinsawicki** [comment]
@jean-christophe-manciot which GitHub service are you experience an issue with?

Are you having problems pushing to GitHub?

This repository is for issues related to the services available from a repository's Settings page.

**Comment by kevinsawicki** [comment]
Closing this out since this looks like a Git authentication issue unrelated to the services included in this repository.

Also, please [contact support](https://github.com/contact) if you are still having issues pushing or pulling from your repositories.
