### ISSUE TITLE
IRC hook does not notify about issues opened or closed

### ISSUE THREAD

**Issue by AlissaSquared** [github/github-services#1090]
I tested this in my personal channel on Esper and cannot confirm on other networks. The IRC bot joins for events such as me committing or merging, but if I were to add an issue, it is not posted to the channel. The bot does not join the channel either. I have neither the experience nor the time to edit the Ruby script to get it working.

**Comment by keavy** [comment]
@AlissaSquared can you provide a link to the repo, and the issue that you opened and closed? If you could also provide a list of steps for reproducing the bug, that would help us to test the exact same behavior you're trying. Thanks!

**Comment by AlissaSquared** [comment]
The repository is [here](https://github.com/AlissaSquared/lua-ncurses/), and [here](https://github.com/AlissaSquared/lua-ncurses/issues/1) is the issue. I simply added and then closed the issue, and neither were notified to my channel.
(Yes, I know, I'm real mature when testing/commenting on test issues..)

**Comment by keavy** [comment]
@AlissaSquared it looks like that repository is only setup to receive `push` and `pull_request` events. The full list of available events can be found [here](https://developer.github.com/webhooks/#events). If you have difficulty setting things up, you can contact support via https://github.com/support

**Comment by rr-** [comment]
I ran across similar issue. I'm confused by @keavy's response - the linked tutorial concerns web hooks, not service hooks, and IRC integration is a service hook...?

**Comment by davidcelis** [comment]
Hey @rr-! Sorry about the confusion. Both service hooks and web hooks deal with the same hook events, which are listed in the
