### ISSUE TITLE
AWS CodeDeploy service fails with no further explanation

### ISSUE THREAD

**Issue by raulastu** [github/github-services#1092]
I've setup AWS CodeDeploy as this blog says:
https://blogs.aws.amazon.com/application-management/post/Tx33XKAKURCCW83/Automatically-Deploy-from-GitHub-Using-AWS-CodeDeploy

I've configured everything (many times) and still receive this when I click on 'Test Service'

"Oops, we weren’t able to send the test payload: AWS CodeDeploy doesn't support the push event."

I've setup the IAM user and copy-pasted the access key and secret one. I have my AWS application and deployement group in lowercase (There was another issue with cases https://forums.aws.amazon.com/thread.jspa?messageID=597193
) and still don't get to know the root cause.

Can you provide the log for when I make the 'Test Service' and get the following error

"Oops, we weren’t able to send the test payload: AWS CodeDeploy doesn't support the push event."

PS: The GitHub Auto-Deployment service works as it has a checkmark to the side.

Thanks in advance

**Comment by kdaigle** [comment]
Hey @raulastu! Would you mind contacting https://github.com/support for this? We'll be able to help you much more easily through that venue. :smile: Thanks!

**Comment by SANDHBill** [comment]
Im having the same problem:( Have you had a succcess?

**Comment by raulastu** [comment]
This was my error:

Thanks.

I think I see what's causing this -- can you please make the
deployment_group setting in the AWS Code Deploy service match the value of
the environments setting of the GitHub Auto-Deployment service? Currently
those two do not match.

Let me know if that doesn't help.

Cheers,
Ivan
