### ISSUE TITLE
repo owner not passed with opening of pull requests

### ISSUE THREAD

**Issue by Zarthus** [github/github-services#1096]
Hey everyone, a while ago my pull request (https://github.com/github/github-services/pull/1070) got merged.

Recently, I noticed some of the bots connecting have a broken realname when they shouldn't have, and have been able to trace down the behaviour and reproduce it.

The issue:

Bots that connect sometimes do not have a repo_owner, retrieved by getting  `payload["repository"]["owner"]["name"]`

When does this happen?:

From what I've been able to consistently reproduce, when a pull request gets opened.

What does it look like?:

```
12:18:54               --> │ zarthus-git-org-t (GitHub IRCBot - /test) (~zarthus-g@192.30.252.45) 
                           │ has joined #myChannel                                                  
12:18:54 zarthus-git-org-t │ [test] Zarthus opened pull request #3: Revert "Test"                 
                           │ (master...revert-2-test2) http://git.io/vCdtW                        
12:18:54               <-- │ zarthus-git-org-t (~zarthus-g@192.30.252.45) has left #myChannel       
```

(note the "GitHub IRCBot - /test" rather than "GitHub IRCBot - test-org-d/test")

It does not matter if it is an organisation account or an user repository. It is always in the open pull request event.

----

As far as I am able to find out, this might simply be a problem that the Pull Request does not send owner data, and the best fix I can think of is would be to send that data along. However, https://developer.github.com/v3/activity/events/types/#pullrequestevent implies that the data *is* sent, so I imagine someone else would have to confirm or deny this.

If this is intended, the tests of the project should be reflective of this, and should fail when we're trying to interact with opening of pull requests.

If this should be accounted for in the code I wrote - I'm happy to submit another pull request to account for cases where repo_owner might be missing - or perhaps the code I have written is flawed in a way. But I initially opened an issue as I do not think the problem is affecting just me, and it might affect other services as well.

**Comment by keavy** [comment]
Hey @Zarthus, thanks for the detailed information. Will take a look, and we'll update with more thoughts soon.

**Comment by keavy** [comment]
@Zarthus, could you contact [support](https://github.com/contact), with specific events/repositories where you see this happening? We can investigate further from there. Thanks!

**Comment by Zarthus** [comment]
@keavy: I've contacted support. I hope it's useful!
