### ISSUE TITLE
Use committer's or pusher's name in emails sent from Email service even when send_from_author is false

### ISSUE THREAD

**Issue by izuzak** [github/github-services#1103]
A user mentioned this:

> When send_from_author is false, the emails come from "GitHub <noreply@github.com>". Could they instead be from "My Name <noreply@github.com>", so I can see the author at a glance? You do that with issues ("My Name <notifications@github.com>") but not commits.

I like that idea. Setting send_from_author to true might cause problems in some situations (e.g. this user had problems with the DMARC policy on his domain for commits authored by users with email addresses from that domain), so users sometimes decide to set send_from_author to false, but still want to know who authored/pushed the commits.

**Comment by mikemcquaid** [comment]
@izuzak Interesting idea. My only worry is that we may break user's current email filtering in doing so. What do you think?

**Comment by izuzak** [comment]
> My only worry is that we may break user's current email filtering in doing so. What do you think?

Yeah, that's very possible. :cold_sweat: Perhaps we could make it an option so that users can pick the behavior they want?

**Comment by mikemcquaid** [comment]
> Yeah, that's very possible.  Perhaps we could make it an option so that users can pick the behavior they want?

I personally am generally :-1: on options like this but if we can work out to explain it clearly enough that it's obvious what each do that could be :ok:

**Comment by izuzak** [comment]
> I personally am generally :-1: on options like this 

Just to make sure I understand -- what do you mean by "options _like this_" (do you mean options for small things like these)? And why are you :-1: on these kinds of options?

I'm not a huge fan of adding more checkboxes, but I'm also not against it in cases where they can improve the user experience and we don't want to break the current behavior. That said, I don't think this is a high priority thing.

**Comment by mikemcquaid** [comment]
@izuzak Apologies for my lack of clarity. I meant options that could be considered delegation of design decisions to the user i.e. rather than picking a best option and going with that you let them choose between two options rather than making the choice yourself. Given our guidelines in https://github.com/github/github-services/blob/master/CONTRIBUTING.md#updating-an-existing-service and that we'll probably break backwards compatibility without an option I think we should pass on this.

**Comment by mikemcquaid** [comment]
@izuzak I think I'm going to close this out as discussed but please feel free to reopen if you disagree.

**Comment by izuzak** [comment]
Sure, thanks @mikemcquaid. :ok_hand: I'll add Halp links here if we get more requests for this.
