### ISSUE TITLE
IRC bot leaked nickserv password

### ISSUE THREAD

**Issue by cpuguy83** [github/github-services#1104]
The IRC bot setup through our repo > account settings> services leaked it's NickServ password into the IRC channel today... 
https://botbot.me/freenode/docker-dev/2015-11-12/?msg=53988321&page=2

**Comment by kdaigle** [comment]
Given moments before the password was put in chat there was a user who renamed to `docker-bot`, is it possible this wasn't the IRC service?

It looks like the IRC service [only private messages the password](https://github.com/github/github-services/blob/master/lib/services/irc.rb#L77). We do rely on the community to help with these services however so please let me know if I've misdiagnosed this. :smile:

**Comment by cpuguy83** [comment]
oh geezum, I totally mised that, I have joins/parts/nick changes etc turned off on my client.
Yep, seems like it was something else.

Sorry for the noise!

**Comment by kdaigle** [comment]
No problem! :sparkles: Have a great weekend.
