### ISSUE TITLE
Commit message with ampersand is truncated in Asana task

### ISSUE THREAD

**Issue by steven-sortable** [github/github-services#1107]
If a commit message contains an ampersand, the comment generated in the Asana task is truncated at that ampersand.

I suspect the fix is to url-encode the text argument at
https://github.com/github/github-services/blob/667324da257fae3203370fd082a1c86955b58708/lib/services/asana.rb#L55

**Comment by jasonrudolph** [comment]
Thanks for logging this issue, @steven-sortable. And thanks for recommending a solution. Would you be willing to open a pull request to fix this issue? If so, I'd be happy to review it and offer feedback.

**Comment by steven-sortable** [comment]
Sure, if necessary.  The only thing is, I don't know any Ruby.  I can try
to feel my way through if you want, but maybe there's a more efficient way?

**Comment by Tonkpils** [comment]
I've tested this and it doesn't seem to be an issue. 
![image](https://cloud.githubusercontent.com/assets/1507561/11795818/0f3d1238-a276-11e5-9b53-2c090aa90a24.png)

**Comment by steven-sortable** [comment]
Ampersand is '&', not '@'.

**Comment by Tonkpils** [comment]
> Ampersand is '&', not '@'.

Oh, whoops, I feel dumb about that. I'll test it out and attempt a fix at it

**Comment by steven-sortable** [comment]
Great, thanks!
