### ISSUE TITLE
Amazon SQS doesn't send event in message_attributes

### ISSUE THREAD

**Issue by jwhitcraft** [github/github-services#1121]
# Problem
When using the SQS service, it doesn't send which event was fired as part of the Message Attributes, so it's hard to determine which service event was triggered.

# Solution
Change
```ruby
queue.send_message(clean_for_json(payload))
```
to this
```ruby
    sqs.send_message(
      queue_url: queue.url,
      message_body: clean_for_json(payload),
      message_attributes: {
        'X-Github-Event' => { string_value: event, data_type: 'String'}
      }  
    )
```

I can submit a PR, but i'm not sure if this is considered a bug fix or an improvement.

**Comment by mikemcquaid** [comment]
CC other people in the @github/platform team for thoughts here and if there's any other way to obtain this information.

**Comment by mikemcquaid** [comment]
Gentle CC again for the @github/platform team to share some thoughts here.

**Comment by jwhitcraft** [comment]
@mikemcquaid or @github/platform,

I can submit a PR for this if it would help push it along?

Thanks!

**Comment by bswinnerton** [comment]
:wave: @jwhitcraft. We have treated the lack of `X-Github-Event` as a bug [in the past](https://github.com/github/github-services/issues/1076#issuecomment-132206193), so I think it would be okay to accept such a fix given our current [contribution guidelines](https://github.com/github/github-services/blob/c7ebee32771af3faed36500dfe239b1605478524/CONTRIBUTING.md#updating-an-existing-service) (which are to only accept PRs for bug fixes or security patches).

If you'd be up for submitting a pull request to solve this, we would greatly appreciate it :smile:.

**Comment by jwhitcraft** [comment]
@bswinnerton and @mikemcquaid 

I submitted a PR for this.
