### ISSUE TITLE
auto-deploy service doesn't use status_contexts

### ISSUE THREAD

**Issue by ejholmes** [github/github-services#1129]
Currently, the UI for the autodeploy hook allows you to provide a comma separated list of status_contexts that should be green for an auto deployment to happen. Currently, this field isn't used at all in https://github.com/github/github-services/blob/master/lib/services/auto_deploy.rb and a deployment will be triggered on _any_ green status update.

The behavior I would expected would be to be able to provide multiple status contexts and only have an auto deploy triggered when all status contexts turn green.

This field has been in the UI for going on a year now with no implementation. Is this hook going to be maintained by someone at github moving forward?

**Comment by ejholmes** [comment]
On a side note, I think a valuable first step would be to only allow 1 commit status in the status_contexts field, which would be easy to implement support for.

**Comment by kdaigle** [comment]
@ejholmes we're going to take a look at this. I'll let you know once we have an update on when and how we'll get this fixed up. :smile:

We may move to remove the field since it's not actually used and re-add it once the field *is* used to avoid more confusion. :space_invader:

**Comment by ejholmes** [comment]
Awesome. Thanks for the update @kdaigle!
