### ISSUE TITLE
Asana is deprecating API keys

### ISSUE THREAD

**Issue by jawaidss** [github/github-services#1132]
The GitHub-Asana integration should switch from API keys to OAuth or personal access tokens.

https://asana.com/guide/help/api/api#gl-api-key
https://github.com/github/github-services/blob/master/lib/services/asana.rb

**Comment by khatchad** [comment]
I am currently using this feature of Asans. Please upgrade so I don't lose it. Thanks.

**Comment by kdaigle** [comment]
We rely on the community to keep integrations like Asana's running as we don't use these tools internally. It looks like @timurvafin @Tonkpils @yegg have all contributed to the Asana service recently. Would any of you be interested in tackling the move to OAuth tokens? :smile:

**Comment by mikemcquaid** [comment]
We may accept a PR for this but I'm closing this out for now.
