### ISSUE TITLE
Atlasssian HipChat - docs/hipchat deep link is dead

### ISSUE THREAD

**Issue by mtakacs** [github/github-services#1145]
The file https://github.com/github/github-services/blob/master/docs/hipchat references a documentation page that no longer exists. I'm not sure where this should point anymore or if the integration spoken of in the text even exists at HipChat anymore.

```
Read more here: http://help.hipchat.com/knowledgebase/articles/64389-github-integration
```

**Comment by davidcelis** [comment]
👋 Hi @mtakacs! It looks like in Atlassian's switch to Confluence from the old help.hipchat.com, they dropped some links. While we appreciate the suggestion, we currently [only accept bugfixes and security patches](https://github.com/github/github-services/blob/master/CONTRIBUTING.md#updating-an-existing-service) to github-services. Thanks!

**Comment by glasnt** [comment]
If you're not accepting feature changes, would you accept a bugfix PR to correct the documentation at least?

Something along the lines of: 

```
diff --git a/docs/hipchat b/docs/hipchat
index b722c94..5ba376b 100644
--- a/docs/hipchat
+++ b/docs/hipchat
@@ -1,6 +1,5 @@
-Note: HipChat has a new and improved integration with GitHub. While this
-service will continue to work, you really should check out the new integration.
-Read more here: http://help.hipchat.com/knowledgebase/articles/64389-github-integration
+Note: Atlassian provides it's own native integration for GitHub.
+Read more here: https://hipchat.com/addons/github-for-hipchat
```

**Comment by mikemcquaid** [comment]
@glasnt Yeh, seems reasonable, thanks!
