### ISSUE TITLE
Regarding contributions

### ISSUE THREAD

**Issue by iamshubh22** [github/github-services#1146]
Maybe this is not the right place to ask for the issue but currently the "Longest streak" shows dates without `year`. Rather it should be showing dates with year so that it is more clear about the duration of the longest streak. Same applies to "Current streak".

![screenshot](https://cloud.githubusercontent.com/assets/13465950/14229091/2c878918-f947-11e5-882e-42ef1490fa4e.jpg)

**Comment by tarebyte** [comment]
@iamshubh22 the best place to raise a question about this would be contacting [GitHub support](https://github.com/contact).

Thanks!
