### ISSUE TITLE
SQS only accepts :push events

### ISSUE THREAD

**Issue by jwhitcraft** [github/github-services#1149]
Right now SQS only accepts push events which isn't ideal becuase or CI servers sit behind a firewall and we have an Internal SQS listener that pushes the events out to it for `pull_request`, `issue_comment` and `push`.

I'm guessing that this can't be updated to support more default events 

eg adding

```ruby
default_events :push, :pull_request, :issue_comment
```

**Comment by jwhitcraft** [comment]
@bswinnerton ?? I can issue a PR, but i'm guessing that this will not be considering a bug.

**Comment by mikemcquaid** [comment]
@jwhitcraft Yeh, unfortunately this would be considered a feature so we're pass on fixing it. Sorry :sob:

**Comment by mikemcquaid** [comment]
For future reference the [Contributing guidlines](https://github.com/github/github-services/blob/master/CONTRIBUTING.md) may help answer some of this stuff. Apologies again.

**Comment by jwhitcraft** [comment]
Ya, i saw that, i was just hoping. Thanks again!
