### ISSUE TITLE
IRC hook: insufficient message when pushing a commit to multiple branches

### ISSUE THREAD

**Issue by o11c** [github/github-services#668]
When pushing a new commit to multiple branches, the IRC hook does not mention that. Rather, it implies that only the *existing* commit on one of the branches has been pushed to the other.

push some change to the 'test' branch
IRC message is good
> [10:34:11] --> github-tmw (~github-tm@192.30.252.48) has joined #themanaworld-dev
> [10:34:11] -- Notice(github-tmw): [tmwa] o11c pushed 3 new commits to test: http://git.io/EIqnNA
> [10:34:11] -- Notice(github-tmw): tmwa/test d2c34c4 Ben Longbons: Make some npc errors better
> [10:34:11] -- Notice(github-tmw): tmwa/test d3beae7 Ben Longbons: Add dumpers for the rest of the stack types
> [10:34:11] -- Notice(github-tmw): tmwa/test 23c0f35 Ben Longbons: Refactor npc event timers to have an expired state...
> [10:34:11] <-- github-tmw (~github-tm@192.30.252.48) has left #themanaworld-dev
 
push that same changeset to the 'master' branch
IRC message is good
> [11:00:38] --> github-tmw (~github-tm@192.30.252.52) has joined #themanaworld-dev
> [11:00:38] -- Notice(github-tmw): [tmwa] o11c merged test into master: http://git.io/qfZLPQ
> [11:00:38] <-- github-tmw (~github-tm@192.30.252.52) has left #themanaworld-dev
 
push a new commit to both branches
IRC message is bad, but the git.io link is good
> [11:34:09] --> github-tmw (~github-tm@192.30.252.52) has joined #themanaworld-dev
> [11:34:10] -- Notice(github-tmw): [tmwa] o11c merged master into test: http://git.io/8intsg
> [11:34:10] <-- github-tmw (~github-tm@192.30.252.52) has left #themanaworld-dev

(I think the "merged X into Y" depends on the order you mention on the command line, `git push origin master test` vs `git push origin test master`)

**Comment by kdaigle** [comment]
> If I am correct, the fundamental issue is something that can't be solved by compliant IRC servers, and can't be solved by the services library unless all service hooks are somehow run serially.

That sounds right. Right now, events are not guaranteed to be run serially and so it looks like we'll have to close this issue. If anything changes in the future, we can look at this again.

**Comment by titanous** [comment]
@kdaigle The bug has not been fixed, why close the issue?

**Comment by kdaigle** [comment]
@titanous assuming the spelunking done by @o11c is correct, we can't guarantee that the payloads received by `github-services` will be serial. I closed the issue because it appeared this *can't* be fixed.

If that diagnosis is incorrect and this is something that can be fixed within the `irc` service, we'd love it if you or anyone else in the community can tackle a fix by submitting a Pull Request. We rely on the community to keep these services in tip top shape as we don't use many of these internally at GitHub. :smile:
