### ISSUE TITLE
IRC Hook: Use `ref_name` instead of `branch_name` and call the filter field `ref_regexes`

### ISSUE THREAD

**Issue by nevik** [github/github-services#773]
It was just brought up in the IRC channel whether the `branch_regexes` field can be used to filter tag names as well.

After some trying we found out that it does, and after some hunting around the code (I'm *really* not a Ruby person), I found out why:
The IRC hook uses `branch_name` for the regexp matches ([on line 324 of `irc.rb`](https://github.com/github/github-services/blob/master/lib/services/irc.rb#L324)), which is aliased to `ref_name` [on line 31 of `push_helpers.rb`](https://github.com/github/github-services/blob/master/lib/service/events/push_helpers.rb#L31).

I therefore suggest to rename the hook property from `branch_regexes` to `ref_regexes` to reflect the field's real functionalty, and to use `ref_name` instead of `branch_name` in the code to remove a level of confusion to someone not knowing the aliases in place, especially because the functionality applies to both branches and tags.

I am not at all experienced with Ruby, so I am not suggesting the code fix myself, as I have no way of testing it (I certainly don't want to set up a Ruby environment just for this, and I dont know how to run Ruby stuff either). I could provide a version of the file with the suggested replacements made if someone else is willing to test it (and fix it if necessary or tell me how to fix it).

**Comment by kdaigle** [comment]
Unfortunately, renaming options is a very difficult endeavor within `github-services` as it stands right now. I created https://github.com/github/github-services/pull/1072 to document the ability to use refs though. :cake:
