### ISSUE TITLE
Configuring the email service to discriminate based on events

### ISSUE THREAD

**Issue by cwarren-mw** [github/github-services#804]
As I understand it, the email service will send mail for every push that happens on a given repository. Would it be possible/practical to allow users to select which events they want to receive mail about? For example, I'm only concerned with "create" and "delete" events right now, and wouldn't be looking to get mail about every unrelated push that might happen.

Thank you.

**Comment by nicolas33** [comment]
No one working on this for a year... seriously?

**Comment by dmiller-nmap** [comment]
[Nmap project](https://github.com/nmap/nmap) would like to see this feature supported. Specifically, we want notification of new pull requests and issues to be sent to our development mailing list, but not pushes.

**Comment by nicolas33** [comment]
[OfflineIMAP projects](https://github.com/OfflineIMAP/offlineimap) would like to see this feature (all events with discrimination options), too.

**Comment by dashea** [comment]
[rhinstaller](https://github.com/rhinstaller/) would like to see this feature, in particular for pull requests and comments. Ideally there could be a way to send patches to a mailing list when a new pull request is created as well as comments on the pull request.

**Comment by splitbrain** [comment]
:+1:  [DokuWiki](https://github.com/splitbrain/dokuwiki) want s this, too

**Comment by sschuberth** [comment]
For those who are just interested in getting email notifications for new PRs / issues, it might be worth looking at [ReviewNinja](https://github.com/reviewninja/review.ninja) which comes with its own per-repository settings to "Receive emails when a pull request is opened or updated" / "Receive emails when issues are opened or closed".

**Comment by crobinso** [comment]
I just played with ReviewNinja... I don't see any way to configure it to send its emails to an arbitrary email address, just emails associated with your user. So WRT this request it doesn't add anything that you can't already get by starring a repo

**Comment by sschuberth** [comment]
@crobinso Right, I should have been more clear about that. ReviewNinja helps with *my* use-case where I'd like to get email notifications for *some* of my watched projects, and web notifications for others of my watched projects.

But what does starring a repo have to do with notifications? Ever since the [new notification system](https://github.com/blog/1204-notifications-stars), "Stars are a new way to keep track of repositories that you find interesting" and "Notifications are now powered by the repositories you are watching".

**Comment by crobinso** [comment]
Sorry, I meant 'watch' instead of 'star'. Watching a repo generates email notifications of pull request activity at least

**Comment by sschuberth** [comment]
Right, but you can only globally switch between email and web notifications for watched projects. I'd like to be able to choose between email and web notifications on a per project basis. This is where ReviewNinja helped me.

**Comment by crobinso** [comment]
Oh, gotchya, didn't realize that

**Comment by kdaigle** [comment]
Thank you for everyone's feedback on this issue. :sparkles: The email service has been relatively simple from the beginning and it is one of our oldest services. Getting many different notification types like have been requested in this thread would probably be better served by a change within GitHub.com and not updating this service. The email service as it stands is very singularly focused: email me when a push happens on my repository.

If you have a specific use-case for email notifications, you can always share them with us at https://github.com/support. By contacting us there, we'll be able to get your request in front of the specific team who could potentially implement that type of notification. The `github-services` repository and its issues are for bugs with existing services so it isn't the best avenue for feature requests. :smile:

**Comment by nicolas33** [comment]
How to turn a blind eye to a one year old request while keeping up appearances...

**Comment by Tyrael** [comment]
sigh

**Comment by Bluerise** [comment]
Support tells me to configure an email filter instead... Well done, Github.
