### ISSUE TITLE
Add option for comment & close in one step in Bugzilla service

### ISSUE THREAD

**Issue by lildude** [github/github-services#855]
At the moment, when a commit is pushed to a repository with the Bugzilla webhook configured and the commit contains the magic keywords needed to close a bug, 4 xmlrpc calls are made:

* [User.login](https://github.com/github/github-services/blob/master/lib/services/bugzilla.rb#L65) to log the configured user in.
* [Bug.comments](https://github.com/github/github-services/blob/master/lib/services/bugzilla.rb#L89) to check the current comments don't mention the commit.
* [Bug.add_comment](https://github.com/github/github-services/blob/master/lib/services/bugzilla.rb#L110) to add a comment.
* [Bug.update](https://github.com/github/github-services/blob/master/lib/services/bugzilla.rb#L121) to close the bug.

This works well in most situations, but it all falls down, and quietly, when a Bugzilla installation requires a comment in the closure update.

The Bugzilla webhook should give the option to merge the last two, `Bug.add_comment` and `Bug.update` into a single call, `Bug.update`, which adds the comment and closes the bug in one step.

**Comment by kdaigle** [comment]
@lildude I'm going to close this PR due to its age. If you're interesting in still creating a PR for this that meets our [contribution guidelines](https://github.com/github/github-services/blob/master/CONTRIBUTING.md), go for it! :smile:
