### ISSUE TITLE
Jenkins Git plugin doesn't support SSL on port different than 443

### ISSUE THREAD

**Issue by vincenzobluesparklabs** [github/github-services#893]
I found this issue during the configuration of our Jenkins server.
I tried both self-signed and CA Trusted certificate but if the jenkins server listen on a non-standard port (in my case port 8081), the Jenkins Git plugin doesn't send the payload.
But if i turn off the SSL and use port 8081, plugin works fine.
I resolved the issue by configuring apache as https proxy for jenkins.

**Comment by kdaigle** [comment]
If you're still experiencing this, could you contact https://github.com/support to go through the specifics of your service installation? Thanks!
