### ISSUE TITLE
X-Github-* case sensitivity

### ISSUE THREAD

**Issue by AustinDizzy** [github/github-services#909]
On the repository settings under Webhooks & Services and Manage Webhooks, the "Recent Deliveries"  panel reports the request headers in mixed case sensitivity. For example, it reports headers as "X-GitHub-Event" instead of "X-Github-Event". This can be cumbersome when debugging problems with a webhook that has a case sensitive HTTP library like Go's built-in HTTP library.

The documentation seems to be fine but the console on the webhooks settings in the repositories is improperly mixed case. I don't know if this is the correct repository to report the issue in, but it seemed to be the most relevant to the issue.

It would be most beneficial for debugging purposes if the case matched from the documentation.

Thanks.

**Comment by stof** [comment]
HTTP explicitly specifies header names as being case insensitive. So the issue seems to be the Go flawed implementation here

**Comment by kdaigle** [comment]
@stof is correct that [HTTP headers should be case insensitive](https://tools.ietf.org/html/rfc7230#section-3.2). It is possible that the headers in "Recent Deliveries" have not held their casing correctly but I believe this would be something worth fixing in the Go library.
