### ISSUE TITLE
pluggable url shortener (for Github Enterprise)

### ISSUE THREAD

**Issue by mehulkar** [github/github-services#935]
Looks like `git.io` is [hardcoded right now](https://github.com/github/github-services/blob/master/lib/service.rb#L509-L523). On Github Enterprise, even when I don't check the "Long URL" option n the IRC hook, it sends the long url. Not sure if it's just timing out or what?

Would be cool to be able to use a URL shortener of our choice.

**Comment by kdaigle** [comment]
Hey @mehulkar! I passed this on to our Enterprise team to see if this is something they might be able to add in a future release. If you have any questions about this, you can always reach out to your GitHub Enterprise support team. :smile:
