### ISSUE TITLE
Zendesk integration getting 422 response always

### ISSUE THREAD

**Issue by gadybadger** [github/github-services#940]
The Zendesk integration seems to always get a 422 response when credentials are correctly set. Can any other users of this integration confirm?

**Comment by JimMikola** [comment]
Yes we can confirm.  It's been this way since approximately August 2014.  

I submitted a ticket to ZenDesk.  Their response is that ZenDesk has no involvement with this community integration.

I've requested the latest API documentation from ZenDesk to assist with fixing this issue.

**Comment by gadybadger** [comment]
Got it, thanks for the info.

**Comment by kdaigle** [comment]
Based on looking at a few of these installations, I believe the Zendesk integration is working as expected now. If this is still happening, please feel free to open this up again. :cake: Thanks!
