### ISSUE TITLE
Twitter service should preserve double-newlines in commit messages

### ISSUE THREAD

**Issue by domenic** [github/github-services#959]
E.g. in https://twitter.com/streamsstandard/status/526780118052524032 there should be two newlines after .pipeTo(), like there is in the original commit message.

**Comment by kdaigle** [comment]
I believe this is an issue for https://github.com/whatwg/streams. Feel free to re-open if this is meant for GitHub services. :cake:

**Comment by domenic** [comment]
I am the editor for whatwg/streams, so no, this was not meant for that repo. This was meant for GitHub services. I am talking about the service that GitHub built that tweets your commit messages, for which the code exists in this repository.

Please re-open. I cannot do so myself as I am not a repository owner or collaborator.

**Comment by kdaigle** [comment]
@domenic sorry for the confusion. :fearful: 

If you'd like to fix this bug, you can [fork this repository](https://help.github.com/articles/fork-a-repo/) and submit a Pull Request for the change. We rely on the community to make changes to the services in this repository. :smile: You can see the service code here: https://github.com/github/github-services/blob/master/lib/services/twitter.rb

**Comment by domenic** [comment]
Can you reopen the bug in the meantime? And yes, I'm aware the code was there.
