### ISSUE TITLE
https://api.github.com/hooks does not include 'web'

### ISSUE THREAD

**Issue by johnsheehan** [github/github-services#978]
The https://api.github.com/hooks endpoint does not include web. This would be nice so I could get the list of supported_events for it in case it is subject to change in the future.

**Comment by kdaigle** [comment]
Hey @johnsheehan! We don't currently have plans to return "web" as a returned service from `/hooks`. I'll pass your idea about being able to listen for new events within webhooks to the larger team though. In the meantime, your best bet is to watch https://developer.github.com/changes for any updates. :smile:
