### ISSUE TITLE
Try both http and https for hipchat service

### ISSUE THREAD

**Issue by ecliptik** [github/github-services#985]
In the hipchat service module https is hardcoded,

* https://github.com/github/github-services/blob/master/lib/services/hipchat.rb#L56

This is causing an issue on a self-signed enterprise hipchat instance where the ssl handshake fails. Trying to set the server to :80 does not resolve the issue since https still starts a ssl handshake. This has been verified with netcat and packet captures.

Having the service first try https and then fallback to http would be ideal.

**Comment by kdaigle** [comment]
@ecliptik you should try @rmanalan's suggestion (he works at HipChat). :smile: Closing this out as we don't plan on changing anything with the HipChat service.
